### PR TITLE
Bugfix rem.auth tests

### PR DESCRIPTION
**Pull request by Alladin9393**
## Change Description

Fixed rem.auth tests and added new test cases.
 - integrated tests that associated with rem.oracle in rem.auth
 - token distribution control in rem.auth contract and current supply of AUTH credits tests 

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by Alladin9393** [comment]
Build_and_test

**Comment by Alladin9393** [comment]
Build_and_test

**Comment by Alladin9393** [comment]
Build_and_test

**Comment by Alladin9393** [comment]
Build_and_test

**Review by Art17 — APPROVED** [review]

**Comment by Alladin9393** [comment]
Build_and_test

**Pull request merged**
